// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"database/sql"
	"sync"

	"github.com/DueIt-Jasanya-Aturuang/spongebob/domain/repository"
)

type FakeSqlTransactionRepo struct {
	StartTXStub        func(context.Context, *sql.TxOptions) (*sql.Tx, error)
	startTXMutex       sync.RWMutex
	startTXArgsForCall []struct {
		arg1 context.Context
		arg2 *sql.TxOptions
	}
	startTXReturns struct {
		result1 *sql.Tx
		result2 error
	}
	startTXReturnsOnCall map[int]struct {
		result1 *sql.Tx
		result2 error
	}
	TransactionStub        func(context.Context, *sql.TxOptions, func(*sql.Tx) error) error
	transactionMutex       sync.RWMutex
	transactionArgsForCall []struct {
		arg1 context.Context
		arg2 *sql.TxOptions
		arg3 func(*sql.Tx) error
	}
	transactionReturns struct {
		result1 error
	}
	transactionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSqlTransactionRepo) StartTX(arg1 context.Context, arg2 *sql.TxOptions) (*sql.Tx, error) {
	fake.startTXMutex.Lock()
	ret, specificReturn := fake.startTXReturnsOnCall[len(fake.startTXArgsForCall)]
	fake.startTXArgsForCall = append(fake.startTXArgsForCall, struct {
		arg1 context.Context
		arg2 *sql.TxOptions
	}{arg1, arg2})
	stub := fake.StartTXStub
	fakeReturns := fake.startTXReturns
	fake.recordInvocation("StartTX", []interface{}{arg1, arg2})
	fake.startTXMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSqlTransactionRepo) StartTXCallCount() int {
	fake.startTXMutex.RLock()
	defer fake.startTXMutex.RUnlock()
	return len(fake.startTXArgsForCall)
}

func (fake *FakeSqlTransactionRepo) StartTXCalls(stub func(context.Context, *sql.TxOptions) (*sql.Tx, error)) {
	fake.startTXMutex.Lock()
	defer fake.startTXMutex.Unlock()
	fake.StartTXStub = stub
}

func (fake *FakeSqlTransactionRepo) StartTXArgsForCall(i int) (context.Context, *sql.TxOptions) {
	fake.startTXMutex.RLock()
	defer fake.startTXMutex.RUnlock()
	argsForCall := fake.startTXArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSqlTransactionRepo) StartTXReturns(result1 *sql.Tx, result2 error) {
	fake.startTXMutex.Lock()
	defer fake.startTXMutex.Unlock()
	fake.StartTXStub = nil
	fake.startTXReturns = struct {
		result1 *sql.Tx
		result2 error
	}{result1, result2}
}

func (fake *FakeSqlTransactionRepo) StartTXReturnsOnCall(i int, result1 *sql.Tx, result2 error) {
	fake.startTXMutex.Lock()
	defer fake.startTXMutex.Unlock()
	fake.StartTXStub = nil
	if fake.startTXReturnsOnCall == nil {
		fake.startTXReturnsOnCall = make(map[int]struct {
			result1 *sql.Tx
			result2 error
		})
	}
	fake.startTXReturnsOnCall[i] = struct {
		result1 *sql.Tx
		result2 error
	}{result1, result2}
}

func (fake *FakeSqlTransactionRepo) Transaction(arg1 context.Context, arg2 *sql.TxOptions, arg3 func(*sql.Tx) error) error {
	fake.transactionMutex.Lock()
	ret, specificReturn := fake.transactionReturnsOnCall[len(fake.transactionArgsForCall)]
	fake.transactionArgsForCall = append(fake.transactionArgsForCall, struct {
		arg1 context.Context
		arg2 *sql.TxOptions
		arg3 func(*sql.Tx) error
	}{arg1, arg2, arg3})
	stub := fake.TransactionStub
	fakeReturns := fake.transactionReturns
	fake.recordInvocation("Transaction", []interface{}{arg1, arg2, arg3})
	fake.transactionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSqlTransactionRepo) TransactionCallCount() int {
	fake.transactionMutex.RLock()
	defer fake.transactionMutex.RUnlock()
	return len(fake.transactionArgsForCall)
}

func (fake *FakeSqlTransactionRepo) TransactionCalls(stub func(context.Context, *sql.TxOptions, func(*sql.Tx) error) error) {
	fake.transactionMutex.Lock()
	defer fake.transactionMutex.Unlock()
	fake.TransactionStub = stub
}

func (fake *FakeSqlTransactionRepo) TransactionArgsForCall(i int) (context.Context, *sql.TxOptions, func(*sql.Tx) error) {
	fake.transactionMutex.RLock()
	defer fake.transactionMutex.RUnlock()
	argsForCall := fake.transactionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSqlTransactionRepo) TransactionReturns(result1 error) {
	fake.transactionMutex.Lock()
	defer fake.transactionMutex.Unlock()
	fake.TransactionStub = nil
	fake.transactionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSqlTransactionRepo) TransactionReturnsOnCall(i int, result1 error) {
	fake.transactionMutex.Lock()
	defer fake.transactionMutex.Unlock()
	fake.TransactionStub = nil
	if fake.transactionReturnsOnCall == nil {
		fake.transactionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.transactionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSqlTransactionRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.startTXMutex.RLock()
	defer fake.startTXMutex.RUnlock()
	fake.transactionMutex.RLock()
	defer fake.transactionMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSqlTransactionRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.SqlTransactionRepo = new(FakeSqlTransactionRepo)
