// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"database/sql"
	"sync"

	"github.com/DueIt-Jasanya-Aturuang/spongebob/domain/dto"
	"github.com/DueIt-Jasanya-Aturuang/spongebob/domain/model"
	"github.com/DueIt-Jasanya-Aturuang/spongebob/domain/repository"
)

type FakeProfileCfgRepo struct {
	GetProfileCfgByIdStub        func(context.Context, string) (*model.ProfileCfg, error)
	getProfileCfgByIdMutex       sync.RWMutex
	getProfileCfgByIdArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getProfileCfgByIdReturns struct {
		result1 *model.ProfileCfg
		result2 error
	}
	getProfileCfgByIdReturnsOnCall map[int]struct {
		result1 *model.ProfileCfg
		result2 error
	}
	GetProfileCfgBySchedulerStub        func(context.Context, dto.ProfileCfgScheduler) (*[]model.ProfileCfg, error)
	getProfileCfgBySchedulerMutex       sync.RWMutex
	getProfileCfgBySchedulerArgsForCall []struct {
		arg1 context.Context
		arg2 dto.ProfileCfgScheduler
	}
	getProfileCfgBySchedulerReturns struct {
		result1 *[]model.ProfileCfg
		result2 error
	}
	getProfileCfgBySchedulerReturnsOnCall map[int]struct {
		result1 *[]model.ProfileCfg
		result2 error
	}
	StoreProfileCfgStub        func(context.Context, *sql.Tx, model.ProfileCfg) error
	storeProfileCfgMutex       sync.RWMutex
	storeProfileCfgArgsForCall []struct {
		arg1 context.Context
		arg2 *sql.Tx
		arg3 model.ProfileCfg
	}
	storeProfileCfgReturns struct {
		result1 error
	}
	storeProfileCfgReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateProfileCfgStub        func(context.Context, *sql.Tx, model.ProfileCfg) error
	updateProfileCfgMutex       sync.RWMutex
	updateProfileCfgArgsForCall []struct {
		arg1 context.Context
		arg2 *sql.Tx
		arg3 model.ProfileCfg
	}
	updateProfileCfgReturns struct {
		result1 error
	}
	updateProfileCfgReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProfileCfgRepo) GetProfileCfgById(arg1 context.Context, arg2 string) (*model.ProfileCfg, error) {
	fake.getProfileCfgByIdMutex.Lock()
	ret, specificReturn := fake.getProfileCfgByIdReturnsOnCall[len(fake.getProfileCfgByIdArgsForCall)]
	fake.getProfileCfgByIdArgsForCall = append(fake.getProfileCfgByIdArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetProfileCfgByIdStub
	fakeReturns := fake.getProfileCfgByIdReturns
	fake.recordInvocation("GetProfileCfgById", []interface{}{arg1, arg2})
	fake.getProfileCfgByIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProfileCfgRepo) GetProfileCfgByIdCallCount() int {
	fake.getProfileCfgByIdMutex.RLock()
	defer fake.getProfileCfgByIdMutex.RUnlock()
	return len(fake.getProfileCfgByIdArgsForCall)
}

func (fake *FakeProfileCfgRepo) GetProfileCfgByIdCalls(stub func(context.Context, string) (*model.ProfileCfg, error)) {
	fake.getProfileCfgByIdMutex.Lock()
	defer fake.getProfileCfgByIdMutex.Unlock()
	fake.GetProfileCfgByIdStub = stub
}

func (fake *FakeProfileCfgRepo) GetProfileCfgByIdArgsForCall(i int) (context.Context, string) {
	fake.getProfileCfgByIdMutex.RLock()
	defer fake.getProfileCfgByIdMutex.RUnlock()
	argsForCall := fake.getProfileCfgByIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProfileCfgRepo) GetProfileCfgByIdReturns(result1 *model.ProfileCfg, result2 error) {
	fake.getProfileCfgByIdMutex.Lock()
	defer fake.getProfileCfgByIdMutex.Unlock()
	fake.GetProfileCfgByIdStub = nil
	fake.getProfileCfgByIdReturns = struct {
		result1 *model.ProfileCfg
		result2 error
	}{result1, result2}
}

func (fake *FakeProfileCfgRepo) GetProfileCfgByIdReturnsOnCall(i int, result1 *model.ProfileCfg, result2 error) {
	fake.getProfileCfgByIdMutex.Lock()
	defer fake.getProfileCfgByIdMutex.Unlock()
	fake.GetProfileCfgByIdStub = nil
	if fake.getProfileCfgByIdReturnsOnCall == nil {
		fake.getProfileCfgByIdReturnsOnCall = make(map[int]struct {
			result1 *model.ProfileCfg
			result2 error
		})
	}
	fake.getProfileCfgByIdReturnsOnCall[i] = struct {
		result1 *model.ProfileCfg
		result2 error
	}{result1, result2}
}

func (fake *FakeProfileCfgRepo) GetProfileCfgByScheduler(arg1 context.Context, arg2 dto.ProfileCfgScheduler) (*[]model.ProfileCfg, error) {
	fake.getProfileCfgBySchedulerMutex.Lock()
	ret, specificReturn := fake.getProfileCfgBySchedulerReturnsOnCall[len(fake.getProfileCfgBySchedulerArgsForCall)]
	fake.getProfileCfgBySchedulerArgsForCall = append(fake.getProfileCfgBySchedulerArgsForCall, struct {
		arg1 context.Context
		arg2 dto.ProfileCfgScheduler
	}{arg1, arg2})
	stub := fake.GetProfileCfgBySchedulerStub
	fakeReturns := fake.getProfileCfgBySchedulerReturns
	fake.recordInvocation("GetProfileCfgByScheduler", []interface{}{arg1, arg2})
	fake.getProfileCfgBySchedulerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProfileCfgRepo) GetProfileCfgBySchedulerCallCount() int {
	fake.getProfileCfgBySchedulerMutex.RLock()
	defer fake.getProfileCfgBySchedulerMutex.RUnlock()
	return len(fake.getProfileCfgBySchedulerArgsForCall)
}

func (fake *FakeProfileCfgRepo) GetProfileCfgBySchedulerCalls(stub func(context.Context, dto.ProfileCfgScheduler) (*[]model.ProfileCfg, error)) {
	fake.getProfileCfgBySchedulerMutex.Lock()
	defer fake.getProfileCfgBySchedulerMutex.Unlock()
	fake.GetProfileCfgBySchedulerStub = stub
}

func (fake *FakeProfileCfgRepo) GetProfileCfgBySchedulerArgsForCall(i int) (context.Context, dto.ProfileCfgScheduler) {
	fake.getProfileCfgBySchedulerMutex.RLock()
	defer fake.getProfileCfgBySchedulerMutex.RUnlock()
	argsForCall := fake.getProfileCfgBySchedulerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProfileCfgRepo) GetProfileCfgBySchedulerReturns(result1 *[]model.ProfileCfg, result2 error) {
	fake.getProfileCfgBySchedulerMutex.Lock()
	defer fake.getProfileCfgBySchedulerMutex.Unlock()
	fake.GetProfileCfgBySchedulerStub = nil
	fake.getProfileCfgBySchedulerReturns = struct {
		result1 *[]model.ProfileCfg
		result2 error
	}{result1, result2}
}

func (fake *FakeProfileCfgRepo) GetProfileCfgBySchedulerReturnsOnCall(i int, result1 *[]model.ProfileCfg, result2 error) {
	fake.getProfileCfgBySchedulerMutex.Lock()
	defer fake.getProfileCfgBySchedulerMutex.Unlock()
	fake.GetProfileCfgBySchedulerStub = nil
	if fake.getProfileCfgBySchedulerReturnsOnCall == nil {
		fake.getProfileCfgBySchedulerReturnsOnCall = make(map[int]struct {
			result1 *[]model.ProfileCfg
			result2 error
		})
	}
	fake.getProfileCfgBySchedulerReturnsOnCall[i] = struct {
		result1 *[]model.ProfileCfg
		result2 error
	}{result1, result2}
}

func (fake *FakeProfileCfgRepo) StoreProfileCfg(arg1 context.Context, arg2 *sql.Tx, arg3 model.ProfileCfg) error {
	fake.storeProfileCfgMutex.Lock()
	ret, specificReturn := fake.storeProfileCfgReturnsOnCall[len(fake.storeProfileCfgArgsForCall)]
	fake.storeProfileCfgArgsForCall = append(fake.storeProfileCfgArgsForCall, struct {
		arg1 context.Context
		arg2 *sql.Tx
		arg3 model.ProfileCfg
	}{arg1, arg2, arg3})
	stub := fake.StoreProfileCfgStub
	fakeReturns := fake.storeProfileCfgReturns
	fake.recordInvocation("StoreProfileCfg", []interface{}{arg1, arg2, arg3})
	fake.storeProfileCfgMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProfileCfgRepo) StoreProfileCfgCallCount() int {
	fake.storeProfileCfgMutex.RLock()
	defer fake.storeProfileCfgMutex.RUnlock()
	return len(fake.storeProfileCfgArgsForCall)
}

func (fake *FakeProfileCfgRepo) StoreProfileCfgCalls(stub func(context.Context, *sql.Tx, model.ProfileCfg) error) {
	fake.storeProfileCfgMutex.Lock()
	defer fake.storeProfileCfgMutex.Unlock()
	fake.StoreProfileCfgStub = stub
}

func (fake *FakeProfileCfgRepo) StoreProfileCfgArgsForCall(i int) (context.Context, *sql.Tx, model.ProfileCfg) {
	fake.storeProfileCfgMutex.RLock()
	defer fake.storeProfileCfgMutex.RUnlock()
	argsForCall := fake.storeProfileCfgArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProfileCfgRepo) StoreProfileCfgReturns(result1 error) {
	fake.storeProfileCfgMutex.Lock()
	defer fake.storeProfileCfgMutex.Unlock()
	fake.StoreProfileCfgStub = nil
	fake.storeProfileCfgReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProfileCfgRepo) StoreProfileCfgReturnsOnCall(i int, result1 error) {
	fake.storeProfileCfgMutex.Lock()
	defer fake.storeProfileCfgMutex.Unlock()
	fake.StoreProfileCfgStub = nil
	if fake.storeProfileCfgReturnsOnCall == nil {
		fake.storeProfileCfgReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storeProfileCfgReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProfileCfgRepo) UpdateProfileCfg(arg1 context.Context, arg2 *sql.Tx, arg3 model.ProfileCfg) error {
	fake.updateProfileCfgMutex.Lock()
	ret, specificReturn := fake.updateProfileCfgReturnsOnCall[len(fake.updateProfileCfgArgsForCall)]
	fake.updateProfileCfgArgsForCall = append(fake.updateProfileCfgArgsForCall, struct {
		arg1 context.Context
		arg2 *sql.Tx
		arg3 model.ProfileCfg
	}{arg1, arg2, arg3})
	stub := fake.UpdateProfileCfgStub
	fakeReturns := fake.updateProfileCfgReturns
	fake.recordInvocation("UpdateProfileCfg", []interface{}{arg1, arg2, arg3})
	fake.updateProfileCfgMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProfileCfgRepo) UpdateProfileCfgCallCount() int {
	fake.updateProfileCfgMutex.RLock()
	defer fake.updateProfileCfgMutex.RUnlock()
	return len(fake.updateProfileCfgArgsForCall)
}

func (fake *FakeProfileCfgRepo) UpdateProfileCfgCalls(stub func(context.Context, *sql.Tx, model.ProfileCfg) error) {
	fake.updateProfileCfgMutex.Lock()
	defer fake.updateProfileCfgMutex.Unlock()
	fake.UpdateProfileCfgStub = stub
}

func (fake *FakeProfileCfgRepo) UpdateProfileCfgArgsForCall(i int) (context.Context, *sql.Tx, model.ProfileCfg) {
	fake.updateProfileCfgMutex.RLock()
	defer fake.updateProfileCfgMutex.RUnlock()
	argsForCall := fake.updateProfileCfgArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProfileCfgRepo) UpdateProfileCfgReturns(result1 error) {
	fake.updateProfileCfgMutex.Lock()
	defer fake.updateProfileCfgMutex.Unlock()
	fake.UpdateProfileCfgStub = nil
	fake.updateProfileCfgReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProfileCfgRepo) UpdateProfileCfgReturnsOnCall(i int, result1 error) {
	fake.updateProfileCfgMutex.Lock()
	defer fake.updateProfileCfgMutex.Unlock()
	fake.UpdateProfileCfgStub = nil
	if fake.updateProfileCfgReturnsOnCall == nil {
		fake.updateProfileCfgReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateProfileCfgReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProfileCfgRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getProfileCfgByIdMutex.RLock()
	defer fake.getProfileCfgByIdMutex.RUnlock()
	fake.getProfileCfgBySchedulerMutex.RLock()
	defer fake.getProfileCfgBySchedulerMutex.RUnlock()
	fake.storeProfileCfgMutex.RLock()
	defer fake.storeProfileCfgMutex.RUnlock()
	fake.updateProfileCfgMutex.RLock()
	defer fake.updateProfileCfgMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProfileCfgRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.ProfileCfgRepo = new(FakeProfileCfgRepo)
