version: '3.3'

services:
  account-svc:
    container_name: dueit_svc_account
    image: 68f716144124
    ports:
      - '7001:7001'
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true
    networks:
      - dueit_network

networks:
  dueit_network:
    external: true