version: '3.3'

services:
  account-svc:
    container_name: dueit_account_svc
    image: imageid
    ports:
      - '8181:8181'
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true
    networks:
      - dueit_network

networks:
  dueit_network:
    external: true