package exception

var (
	LogErrOpenConnDB = "ERROR OPEN CONNECTION DB"
	LogErrCloseConn  = "ERROR CLOSE CONNECTION DB FOR RETURNING TO POOL"
	LogErrCloseStmt  = "ERROR CLOSE PREPARED STATEMENT FOR FREE TO MEMORY"
	LogErrCloseRows  = "ERROR CLOSE ROWS FOR FREE FOR DATA"
	LogErrScanning   = "ERROR SCANNING DATA"
	LogErrSTMT       = "ERROR START PREPARED STATEMENT"
	LogErrExec       = "ERROR EXEC TO DATA"
	LogErrQuery      = "ERROR QUERY TO DATA"
	LogErrStartTx    = "ERROR START TRANSACTION"
	LogErrTx         = "ERROR TRANSACTION"
	LogErrTxRollback = "ERROR ROLLBACK TRANSACTION"
	LogErrTxCommit   = "ERROR COMMIT TRANSACTION"
	LogErrTxStart    = "CANNOT START TRANSACTION"

	LogErrMinioConn = "ERROR OPEN CONNECTION MINIO"
	LogErrMinioPut  = "ERROR MINIO PUT OBJECT"
	LogErrMinioDel  = "ERROR MINIO REMOVE OBJECT"

	LogInfoTxRollback = "TRANSACTION ROLLBACK"
	LogInfoTxCommit   = "TRANSACTION COMMIT"
)
