name: account svc deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: install dependency
        run: go mod download

      - name: run test
        run: make test